### ISSUE TITLE
Doesn't work with GitHub Pages.

### ISSUE THREAD

**Issue by ghost** [allizad/jekyll-webpack#7]
Under `_config.yml` , you've set `source: <something>` which github overrides by it's default parameters. which makes it impossible to host on github pages.

**Comment by allizad** [comment]
Heyo! Please see https://github.com/allizad/jekyll-webpack/tree/gh-pages for Github pages support.

**Comment by ghost** [comment]
Yes, but you can not host from gh-pages if your url is <username>.github.io

**Comment by allizad** [comment]
@shreyansh-zazz can you be more specific about what problem you're having? gh-pages serves to [username].github.io or [username].github.io/[team]/[repo], so I'm confused by your comment above.

For example, we've deployed this boilerplate to this github-pages site:
- https://omc.github.io/jekyll-elasticsearch-boilerplate/

**Comment by ghost** [comment]
So sorry, I typed the whole thing earlier I don't know how it got missed.

Here's what I wanted to ask.
When you host your website with Jekyll on gh-pages with following link
`(username).github.io` 
Then it must be host direct from master branch. In your case this boilerplate can not be hosted from master branch. Although you have given the `src` and `dest` values to your `_config.yml` but that GitHub override with defaults.

**Comment by allizad** [comment]
I see what you're saying. I think the branch name is misleading here - the `master `branch is just to give people an example of a jekyll-webpack site, and the `gh-pages` branch is an example of how we'd set it up _if_ we were on a brand new project, in master, and going to use the gh-pages Gem. The master branch isn't meant to exclusively give an example of using gh-pages, as there are multiple ways one could host a Jekyll site.

Have you tried using gh-pages to deploy this at your github.io site? If you have and you're having specific errors or need help debugging, please don't hesitate to reach out.
